name: Plugin Release

on:
  push:
    tags:
      - '[0-9]+.[0-9]+.[0-9]+'
  pull_request:
    branches: [ "master" ] # for test only

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v4
      - name: Setup Gradle
        uses: gradle/gradle-build-action@v3
      - name: Set env
        run: echo "RELEASE_VERSION=0.0.1-test" >> $GITHUB_ENV
      #        run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV
      - name: Test
        run: ./gradlew test
      - name: Build Plugin
        run: ./gradlew buildPlugin
      #      - name: Publish Plugin
      #        run: ./gradlew publishPlugin﻿ #do not release yet
      - name: Rename File
        run: mv build/distributions/MockitoToMock-*.zip build/distributions/MockitoToMockPlugin.zip
      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          draft: false
          token: ${{ secrets.TOKEN_GIT }}
          generate_release_notes: true
          tag_name: ${{ github.ref_name }}
          files: |
            build/distributions/MockitoToMockPlugin.zip